package com.parksmart.controller;
import java.time.Instant; import java.util.Map; import java.util.List; import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import jakarta.validation.Valid; import com.parksmart.dto.Requests; import com.parksmart.entity.*; import com.parksmart.service.*;
@RestController @RequestMapping("/api/garages") public class GarageController { private final ParkingService service; private final ClockService clock; private final RateCardService rates; private final ObjectMapper mapper; public GarageController(ParkingService s,ClockService c,RateCardService r,ObjectMapper m){service=s;clock=c;rates=r;mapper=m;}
 @GetMapping public Object all(){return service.garages();}
 @PostMapping public Garage create(@Valid @RequestBody Requests.GarageRequest r){Garage g=new Garage(r.name,r.address,r.firstHourRate,r.extraHourRate,r.dailyCap);g.setCreatedAt(clock.now());return service.saveGarage(g);}
 @GetMapping("/{id}") public Garage one(@PathVariable long id){return service.garage(id);}
 @PutMapping("/{id}") public Garage update(@PathVariable long id,@Valid @RequestBody Requests.GarageRequest r){Garage g=service.garage(id);g.setName(r.name);g.setAddress(r.address);g.setFirstHourRate(r.firstHourRate);g.setExtraHourRate(r.extraHourRate);g.setDailyCap(r.dailyCap);return service.saveGarage(g);}
 @GetMapping("/{id}/rates") public Object rates(@PathVariable long id){return rates.find(id);}
 @PostMapping(value="/{id}/rates/import",consumes="text/plain") public Object importText(@PathVariable long id,@RequestBody String text){return rates.importText(id,text);}
 @PostMapping(value="/{id}/rates/import",consumes="multipart/form-data") public Object importFile(@PathVariable long id,@RequestPart("file") MultipartFile file)throws java.io.IOException{return rates.importText(id,new String(file.getBytes(),java.nio.charset.StandardCharsets.UTF_8));}
 @PostMapping(value="/{id}/rates/import",consumes="application/json") public Object importJson(@PathVariable long id,@RequestBody JsonNode body){return rates.importRows(id,body);}
 @GetMapping("/{id}/spots") public Object spots(@PathVariable long id){return service.spots(id);}
 @PostMapping("/{id}/spots") public Object addSpots(@PathVariable long id,@Valid @RequestBody Requests.SpotsRequest r){return service.addSpots(id,r);}
 @GetMapping("/{id}/availability") public Object availability(@PathVariable long id,@RequestParam(required=false) SpotType type){return service.availability(id,type);}
 @PostMapping("/{id}/checkin") public Object checkin(@PathVariable long id,@Valid @RequestBody Requests.CheckInRequest r,Authentication a){ParkingSession s=service.checkIn(id,r,a.getName());return session(s);}
 @PostMapping("/{id}/checkout") public Object checkout(@PathVariable long id,@RequestBody Map<String,String> body,Authentication a){return service.checkOut(id,body.getOrDefault("plate",""),a.getName());}
 @GetMapping("/{id}/quote") public Object quote(@PathVariable long id,@RequestParam String plate){return service.quote(id,plate);}
 @GetMapping("/{id}/sessions/active/{plate}") public Object active(@PathVariable long id,@PathVariable String plate){return service.active(id,plate);}
 @PostMapping("/{id}/sessions/transfer") public Object transfer(@PathVariable long id,@RequestBody Map<String,String> body,Authentication a){SessionTransfer transfer=service.transfer(id,body.getOrDefault("fromPlate",""),body.getOrDefault("toPlate",""),body.get("reason"),a.getName());return transfer(transfer);}
 @GetMapping("/{id}/sessions/{sessionId}/transfers") public Object transfers(@PathVariable long id,@PathVariable long sessionId){service.garage(id);return service.transfers(sessionId).stream().map(this::transfer).toList();}
 @GetMapping("/{id}/sessions") public Object sessions(@PathVariable long id,@RequestParam(required=false) String q,@RequestParam(required=false) String status,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant to,@PageableDefault(size=20,sort="checkedInAt",direction=Sort.Direction.DESC) Pageable page){Page<ParkingSession> p=service.search(id,q,status,from,to,page);return Map.of("content",p.getContent().stream().map(this::session).toList(),"page",p.getNumber(),"size",p.getSize(),"totalElements",p.getTotalElements(),"totalPages",p.getTotalPages());}
 private Map<String,Object> session(ParkingSession s){Map<String,Object> result=new java.util.LinkedHashMap<>();result.put("id",s.getId());result.put("plate",s.getPlate());result.put("vehicleType",s.getVehicleType());result.put("spot",Map.of("id",s.getSpot().getId(),"code",s.getSpot().getCode(),"level",s.getSpot().getLevel(),"type",s.getSpot().getType()));result.put("checkedInAt",s.getCheckedInAt());result.put("checkedOutAt",s.getCheckedOutAt());result.put("hoursBilled",s.getHoursBilled()==null?0:s.getHoursBilled());result.put("fee",s.getFee()==null?0:s.getFee());return result;}
 private Map<String,Object> transfer(SessionTransfer t){Map<String,Object> result=new java.util.LinkedHashMap<>();result.put("id",t.getId());result.put("sessionId",t.getSession().getId());result.put("fromPlate",t.getFromPlate());result.put("toPlate",t.getToPlate());result.put("reason",t.getReason());result.put("transferredAt",t.getTransferredAt());return result;}
}