package com.parksmart.service;
import java.time.*; import java.util.*; import java.util.stream.*; import java.math.BigDecimal; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.parksmart.dto.Requests; import com.parksmart.entity.*; import com.parksmart.exception.ApiException; import com.parksmart.repository.*;
@Service public class ParkingService {
 private final GarageRepository garages; private final SpotRepository spots; private final ParkingSessionRepository sessions; private final UserRepository users; private final ClockService clock; private final RateCardRepository rateCards; private final SessionTransferRepository transfers;
 public ParkingService(GarageRepository g,SpotRepository s,ParkingSessionRepository p,UserRepository u,ClockService c,RateCardRepository rates,SessionTransferRepository t){garages=g;spots=s;sessions=p;users=u;clock=c;rateCards=rates;transfers=t;}
 public Garage garage(long id){return garages.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"GARAGE_NOT_FOUND","Garage not found"));}
 public List<Garage> garages(){return garages.findAll();} public Garage saveGarage(Garage g){return garages.save(g);}
 public List<Spot> spots(long id){garage(id);return spots.findByGarageId(id);} public List<Spot> addSpots(long id,Requests.SpotsRequest r){Garage g=garage(id);return spots.saveAll(r.spots.stream().map(x->new Spot(g,x.level,x.code,x.type)).toList());}
 private String plate(String p){return p.replaceAll("[\\s-]","").toUpperCase(Locale.ROOT);} private SpotType required(VehicleType v){return v==VehicleType.EV?SpotType.EV:v==VehicleType.COMPACT?SpotType.COMPACT:SpotType.STANDARD;}
 private Spot choose(long gid,VehicleType type,Long requested){if(requested!=null){Spot s=spots.findById(requested).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"SPOT_NOT_FOUND","Spot not found"));if(!s.getGarage().getId().equals(gid)||sessions.existsByGarageIdAndActiveSpotId(gid,s.getId())||(type==VehicleType.EV?s.getType()!=SpotType.EV:type==VehicleType.STANDARD?s.getType()!=SpotType.STANDARD:(s.getType()!=SpotType.COMPACT&&s.getType()!=SpotType.STANDARD)))throw new ApiException(HttpStatus.CONFLICT,"SPOT_UNAVAILABLE","Requested spot is unavailable or incompatible");return s;}List<Spot> free=spots.findFree(gid,required(type));if(type==VehicleType.COMPACT&&free.isEmpty())free=spots.findFree(gid,SpotType.STANDARD);if(free.isEmpty())throw new ApiException(HttpStatus.CONFLICT,"NO_SPOT","No compatible spot is available");return free.get(0);}
 @Transactional public ParkingSession checkIn(long gid,Requests.CheckInRequest r,String email){String plate=plate(r.plate);if(sessions.findByGarageIdAndActivePlateKey(gid,gid+":"+plate).isPresent())throw new ApiException(HttpStatus.CONFLICT,"PLATE_ACTIVE","Plate already has an active session");Spot spot=choose(gid,r.vehicleType,r.spotId);ParkingSession p=new ParkingSession();p.setGarage(garage(gid));p.setSpot(spot);p.setPlate(plate);p.setVehicleType(r.vehicleType);p.setCheckedInAt(clock.now());p.setActiveSpotId(spot.getId());p.setActivePlateKey(gid+":"+plate);p.setAttendant(users.findByEmailIgnoreCase(email).orElse(null));try{return sessions.saveAndFlush(p);}catch(DataIntegrityViolationException e){throw new ApiException(HttpStatus.CONFLICT,"CONFLICT","Spot or plate is already active");}}
 private FeeCalculator.Breakdown fee(ParkingSession p,Instant now){RateCard rate=rateCards.findByGarageIdAndSpotType(p.getGarage().getId(),p.getSpot().getType()).orElse(null);return FeeCalculator.calculate(Duration.between(p.getCheckedInAt(),now).toMinutes(),rate==null?p.getGarage().getFirstHourRate():rate.getFirstHourRate(),rate==null?p.getGarage().getExtraHourRate():rate.getExtraHourRate(),rate==null?p.getGarage().getDailyCap():rate.getDailyCap());}
 @Transactional public Map<String,Object> checkOut(long gid,String raw,String email){ParkingSession p=active(gid,raw);Instant now=clock.now();FeeCalculator.Breakdown b=fee(p,now);p.setCheckedOutAt(now);p.setHoursBilled(b.hoursBilled());p.setFee(b.totalFee());p.setClosedBy(ParkingSession.ClosedBy.ATTENDANT);p.setActivePlateKey(null);p.setActiveSpotId(null);sessions.save(p);return result(p,b);}
 public Map<String,Object> quote(long gid,String raw){ParkingSession p=active(gid,raw);return result(p,fee(p,clock.now()));} private Map<String,Object> result(ParkingSession p,FeeCalculator.Breakdown b){return Map.of("id",p.getId(),"plate",p.getPlate(),"durationMinutes",b.durationMinutes(),"hoursBilled",b.hoursBilled(),"fullDays",b.fullDays(),"remainderHours",b.remainingHours(),"remainderFee",b.remainderFee(),"fee",b.totalFee());}
 public ParkingSession active(long gid,String raw){return sessions.findByGarageIdAndActivePlateKey(gid,gid+":"+plate(raw)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"ACTIVE_SESSION_NOT_FOUND","No active session for plate"));}
 @Transactional public SessionTransfer transfer(long gid,String fromRaw,String toRaw,String reason,String email){String from=plate(fromRaw),to=plate(toRaw);if(from.equals(to))throw new ApiException(HttpStatus.BAD_REQUEST,"SAME_PLATE","Source and destination plates must differ");ParkingSession session=active(gid,from);if(sessions.findByGarageIdAndActivePlateKey(gid,gid+":"+to).isPresent())throw new ApiException(HttpStatus.CONFLICT,"PLATE_ACTIVE","Destination plate already has an active session");session.setPlate(to);session.setActivePlateKey(gid+":"+to);sessions.saveAndFlush(session);return transfers.save(new SessionTransfer(session,from,to,reason,clock.now(),users.findByEmailIgnoreCase(email).orElse(null)));}
 public List<SessionTransfer> transfers(long sessionId){return transfers.findBySessionIdOrderByTransferredAtAsc(sessionId);}
 public Map<String,Object> availability(long gid,SpotType filter){garage(gid);List<Spot> all=spots.findByGarageId(gid);Map<String,Object> out=new LinkedHashMap<>();for(SpotType t:SpotType.values())if(filter==null||t==filter){List<Spot> list=all.stream().filter(s->s.getType()==t&&!sessions.existsByGarageIdAndActiveSpotId(gid,s.getId())).toList();out.put(t.name(),Map.of("free",list.size(),"byLevel",list.stream().collect(Collectors.groupingBy(Spot::getLevel,Collectors.counting())),"spots",list.stream().map(Spot::getCode).toList()));}return out;}
 public Page<ParkingSession> search(long gid,String q,String status,Instant from,Instant to,Pageable page){Specification<ParkingSession> s=(root,x,cb)->cb.equal(root.get("garage").get("id"),gid);if(q!=null&&!q.isBlank())s=s.and((r,x,c)->c.like(r.get("plate"),"%"+plate(q)+"%"));if("ACTIVE".equals(status))s=s.and((r,x,c)->c.isNull(r.get("checkedOutAt")));if("COMPLETED".equals(status))s=s.and((r,x,c)->c.isNotNull(r.get("checkedOutAt")));if(from!=null)s=s.and((r,x,c)->c.greaterThanOrEqualTo(r.get("checkedInAt"),from));if(to!=null)s=s.and((r,x,c)->c.lessThanOrEqualTo(r.get("checkedInAt"),to));return sessions.findAll(s,page);}
}